- name: Build Docker image
  run: docker build -t dotnet-selenium-image .
 
- name: Run tests in Docker container
  run: |
    docker run --rm \
      -v ${{ github.workspace }}:/app \
      -w /app \
      dotnet-selenium-image \
      bash -c "dotnet restore && dotnet build --no-restore && dotnet test --logger:\"trx;LogFileName=test-results.trx\" --results-directory:./TestResults"