name: .NET Selenium Tests

on:

  push:

    branches: [ "main" ]

  pull_request:

    branches: [ "main" ]

jobs:

  build-and-test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository

        uses: actions/checkout@v3

      - name: Setup .NET

        uses: actions/setup-dotnet@v4

        with:

          dotnet-version: '8.0.x'

      - name: Setup Chrome and ChromeDriver

        uses: browser-actions/setup-chrome@v1

        with:

          chrome-version: stable

      - name: Restore dependencies

        run: dotnet restore

      - name: Build solution

        run: dotnet build --no-restore

      - name: Install Allure CLI

        run: |

          wget https://github.com/allure-framework/allure2/releases/download/2.34.0/allure-2.34.0.tgz

          tar -zxvf allure-2.34.0.tgz

          sudo mv allure-2.34.0 /opt/allure

          sudo ln -s /opt/allure/bin/allure /usr/bin/allure

      - name: Install NuGet packages for Allure reporting

        run: |

          dotnet add Gobigreviews/Gobigreviews.csproj package Allure.NUnit

          dotnet add Gobigreviews/Gobigreviews.csproj package NUnit

          dotnet add Gobigreviews/Gobigreviews.csproj package NUnit3TestAdapter

          dotnet add Gobigreviews/Gobigreviews.csproj package Microsoft.NET.Test.Sdk

      - name: Run tests with Allure results

        run: dotnet test --no-build --logger:"trx;LogFileName=test-results.trx" --results-directory:./allure-results

      - name: Generate Allure Report

        if: always()

        run: |

          mkdir -p allure-results

          cp -r TestResults/*.trx allure-results/ || true

          allure generate allure-results --clean -o allure-report

      - name: Deploy Allure Report to GitHub Pages 🚀

        if: always()

        uses: peaceiris/actions-gh-pages@v3

        with:

          github_token: ${{ secrets.GITHUB_TOKEN }}

          publish_dir: ./allure-report
 