name: Run .NET Selenium Tests in Docker
 
on:

  push:

    branches: ["main"]

  pull_request:

    branches: ["main"]
 
jobs:

  test-in-docker:

    runs-on: ubuntu-latest
 
    steps:

      - name: Checkout repository

        run: git clone ${{ github.server_url }}/${{ github.repository }} .
 
      - name: Build Docker image

        run: docker build -t dotnet-selenium-tests .
 
      - name: Run tests inside Docker

        run: docker run --rm dotnet-selenium-tests
 
      - name: Archive Allure Report

        if: always()

        run: |

          docker create --name temp dotnet-selenium-tests

          docker cp temp:/app/allure-report ./allure-report

          docker rm temp

 